export const EventsBasicDetails = () => [
    {
        type: "text",
        name: "title",
        label:"Event Title",
        required: true,
        showTooltip: false,
        fullWidth: true,
        variant: "outlined",
        gridProps: { xs: 12 },
    },
    {
        type: "text",
        name: "description",
        label:"Description",
        required: true,
        showTooltip: false,
        fullWidth: true,
        variant: "outlined",
        multiline: true,
        rows:3,
        gridProps: { xs: 12 },
    },
    {
        type: "text",
        name: "venue",
        label:"Venue",
        required: true,
        showTooltip: false,
        fullWidth: true,
        variant: "outlined",
        gridProps: { xs: 6 },
    },
    {
        type: "DatePicker",
        name: "date",
        label:"Date",
        required: true,
        showTooltip: false,
        fullWidth: true,
        variant: "outlined",
        gridProps: { xs: 6 },
    },
    {
        type: "TimePicker",
        name: "startTime",
        label:"Starts at",
        required: true,
        showTooltip: false,
        fullWidth: true,
        variant: "outlined",
        gridProps: { xs: 6 },
    },
    {
        type: "TimePicker",
        name: "endTime",
        label:"Ends at",
        required: true,
        showTooltip: false,
        fullWidth: true,
        variant: "outlined",
        gridProps: { xs: 6 },
    },
    {
        type: "text",
        name: "streetAddress",
        label:"Street address",
        required: true,
        showTooltip: false,
        fullWidth: true,
        variant: "outlined",
        gridProps: { xs: 12 },
    },
    {
        type: "dropdown",
        name: "eventType",
        label:"Event type",
        required: true,
        options: [
            { id: "Workshop", value: "Workshop" },
            { id: "Meeting", value: "Meeting" },
            { id: "Celebration", value: "Celebration" },
        ],
        showTooltip: false,
        fullWidth: true,
        variant: "outlined",
        gridProps: { xs: 12 },
    },
    {
        type: "link",
        name: "attachLink",
        label:"Attach Link",
        required: false,
        showTooltip: false,
        fullWidth: true,
        variant: "outlined",
        gridProps: { xs: 12 },
    },


]