export const SupportServicesDetails = () => [
    {
        type: "text",
        name: "name",
        label:"Support service name",
        required: true,
        showTooltip: false,
        fullWidth: true,
        variant: "outlined",
        gridProps: { xs: 12 },
    },
    {
        type: "text",
        name: "description",
        label:"Description",
        required: true,
        showTooltip: false,
        fullWidth: true,
        variant: "outlined",
        multiline: true,
        rows:3,
        gridProps: { xs: 12 },
    },
    {
        type: "PhoneNumber",
        name: "phone",
        label:"Phone",
        required: true,
        showTooltip: false,
        fullWidth: true,
        variant: "outlined",
        multiline: true,
        rows:3,
        gridProps: { xs: 12 },
    },
    {
        type: "text",
        name: "email",
        label:"Email",
        required: false,
        showTooltip: false,
        fullWidth: true,
        variant: "outlined",
        gridProps: { xs: 12 },
    },
    {
        type: "text",
        name: "website",
        label:"Website",
        required: false,
        showTooltip: false,
        fullWidth: true,
        variant: "outlined",
        gridProps: { xs: 12},
    },

]